Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -99,11 +99,6 @@ jobs:
   run-master:
     runs-on: ubuntu-latest
     needs: start-slave
-    env:
-      SLAVE_IP: ${{ needs.start-slave.outputs.slave_ip }}
-      JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/11.0.23-9/x64
-      JAVA_HOME_11_X64: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/11.0.23-9/x64
-      JMETER_HOME: /home/runner/work/Distributed-testing/Distributed-testing/apache-jmeter-5.5
     steps:
       - name: Checkout code
         uses: actions/checkout@v2
@@ -127,28 +122,25 @@ jobs:
           echo "$JMETER_HOME/bin" >> $GITHUB_PATH
         shell: bash
 
-      - name: Wait for Slave to Start
-        run: |
-          echo "Waiting for JMeter Slave to start"
-          sleep 60
-        shell: bash
-
       - name: Configure JMeter Master
         run: |
+          SLAVE_IP=${{ needs.start-slave.outputs.slave_ip }}
           echo "Configuring JMeter Master"
-          echo "remote_hosts=${{ env.SLAVE_IP }}:1099" >> $JMETER_HOME/bin/user.properties
+          echo "remote_hosts=${SLAVE_IP}:1099" >> $JMETER_HOME/bin/user.properties
           echo "server.rmi.ssl.disable=true" >> $JMETER_HOME/bin/user.properties
         shell: bash
 
       - name: Test Connection to JMeter Slave
         run: |
+          SLAVE_IP=${{ needs.start-slave.outputs.slave_ip }}
           echo "Testing connection to JMeter Slave"
-          nc -zv ${{ env.SLAVE_IP }} 1099 || (echo "Unable to connect to JMeter Slave on port 1099" && exit 1)
+          nc -zv $SLAVE_IP 1099 || (echo "Unable to connect to JMeter Slave on port 1099" && exit 1)
         shell: bash
 
       - name: Run JMeter Test (Master)
         run: |
+          SLAVE_IP=${{ needs.start-slave.outputs.slave_ip }}
           echo "Running JMeter Test"
-          $JMETER_HOME/bin/jmeter -n -t Demo.jmx -R${{ env.SLAVE_IP }}:1099 -l test-results.jtl
+          $JMETER_HOME/bin/jmeter -n -t Demo.jmx -R${SLAVE_IP}:1099 -l test-results.jtl
           cat test-results.jtl
         shell: bash
